CREATE DATABASE CINEMA;
USE CINEMA;
DROP DATABASE CINEMA	
CREATE TABLE MOVIES(
    ID INT PRIMARY KEY IDENTITY,
    MOVIENAME NVARCHAR(50) NOT NULL,
    MOVIEPRICE INT NOT NULL,
    STARTDATE INT NOT NULL,
    ENDDATE INT NOT NULL
);

CREATE TABLE ROOMS(
    ID INT PRIMARY KEY IDENTITY,
    ROOMNAME NVARCHAR(50) NOT NULL,
    CHAIRNUMBER INT NOT NULL,
    MOVIEID INT FOREIGN KEY REFERENCES MOVIES(ID)
);

CREATE TABLE TICKETS(
    ID INT PRIMARY KEY IDENTITY,
    TICKETNAME INT FOREIGN KEY REFERENCES MOVIES(ID),
    TICKETNUMBER INT FOREIGN KEY REFERENCES ROOMS(ID)
);

CREATE VIEW us_cinemas AS
SELECT R.ROOMNAME, M.MOVIENAME, R.CHAIRNUMBER AS 'TICKETNUMBER', M.STARTDATE, M.ENDDATE
FROM ROOMS R
JOIN TICKETS T ON R.ID = T.TICKETNUMBER
JOIN MOVIES M ON M.ID = T.TICKETNAME;
SELECT * FROM us_cinemas